# Generated by Django 6.0.2 on 2026-02-19 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_address', models.TextField()),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('years_of_experience', models.CharField(max_length=50)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_salary', models.IntegerField()),
                ('pay_type', models.CharField(choices=[('hourly', 'Hourly'), ('salary', 'Salary')], max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('overall_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('work_life_balance', models.DecimalField(decimal_places=1, max_digits=2)),
                ('salary_benefits', models.DecimalField(decimal_places=1, max_digits=2)),
                ('management', models.DecimalField(decimal_places=1, max_digits=2)),
                ('workplace_happiness', models.DecimalField(decimal_places=1, max_digits=2)),
                ('career_growth', models.DecimalField(decimal_places=1, max_digits=2)),
                ('staffing_levels', models.DecimalField(decimal_places=1, max_digits=2)),
                ('patient_care_quality', models.DecimalField(decimal_places=1, max_digits=2)),
                ('safety', models.DecimalField(decimal_places=1, max_digits=2)),
                ('training_support', models.DecimalField(decimal_places=1, max_digits=2)),
                ('pros', models.TextField()),
                ('cons', models.TextField()),
                ('would_recommend', models.BooleanField(default=True)),
                ('date_posted', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.facility')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
